server:
  port: 8086
spring:
  cloud:
    gateway:
      routes:
      - id: GUEST-SERVICE
        uri: http://localhost:8081
        predicates:
        - Path=/guests/**
      - id: HOTEL-SERVICE
        uri: http://localhost:8080
        predicates:
        - Path=/hotels/**
      - id: RESERVATION-SERVICE
        uri: http://localhost:8082
        predicates:
        - Path=/reservations/**
      - id: PAYMENT-SERVICE
        uri: http://localhost:8083
        predicates:
        - Path=/payments/**
  application:
    name: CLOUD-GATEWAY