spring:
  cloud:
    config:
      server:
        git:
          
          uri: https://github.com/NikhilLella/config-server-properties
          clone-on-start: true
          skip-ssl-validation: true
       

          
server:  port: 8888
  
